kind: PersistentVolume
apiVersion: v1
metadata:
  name: jenkins-volume
  labels: 
    type: local
spec: 
  capacity:
    storage: 20Gi
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/rsacal/kube/jenkins/data"
